# Generated by Django 4.0.1 on 2022-02-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_students_fname_students_lname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myusers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=30)),
                ('join_date', models.DateField()),
                ('login_time', models.TimeField()),
                ('is_login', models.BooleanField(default=False)),
            ],
        ),
    ]
