# Generated by Django 4.0.1 on 2022-02-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_myusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='email',
            field=models.CharField(default='', max_length=254, unique=True),
        ),
    ]
