# Generated by Django 4.0.1 on 2022-02-02 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_myusers_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='track_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crud.tracks'),
        ),
    ]
