# Generated by Django 4.0.1 on 2022-02-02 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_tracks_students_track_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='track_id',
            new_name='trackid',
        ),
        migrations.RenameField(
            model_name='tracks',
            old_name='id',
            new_name='trackid',
        ),
    ]
