# Generated by Django 4.0.1 on 2022-02-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_remove_students_trackid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='fname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='lname',
            field=models.CharField(max_length=30),
        ),
    ]
