# Generated by Django 4.0.1 on 2022-02-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_alter_students_fname_alter_students_lname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='id',
            new_name='sid',
        ),
    ]
