# Generated by Django 4.0.1 on 2022-02-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0015_rename_id_students_sid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='sid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='students',
            name='fname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='lname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
