# Generated by Django 4.0.1 on 2022-02-02 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0016_rename_sid_students_id_alter_students_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='trackid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crud.tracks'),
        ),
    ]
